version: '3.8'

services:
  n8n:
    image: n8nio/n8n:${N8N_VERSION}
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_SECURE_COOKIE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true

volumes:
  n8n_data:
